### ISSUE TITLE
if you are building a docker image and don't set `docker.image` then your custom image configuration gets filtered out

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#263]
`io.fabric8.maven.docker.AbstractDockerMojo.image` seems to get defaulted to the ${project.artifactId} which is then used to filter out all docker images configured inside the '<configuration>'. This basically means custom sidecar docker builds get filtered out!

This was most surprising - took me a fair bit of debugging to find out why/how this is happening.

```

        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>${fabric8.maven.plugin.version}</version>
        <configuration>
          <images>
            <image>
              <name>THIS MUST MATCH ${docker.image}!!!</name>
              <build>
...
              </build>
            </image>
          </images>
        </configuration>
      
```

The filtering of images in docker-maven-plugin needs to be overridden really (as really we should assume that if an <image> has a name, then its OK :).

This line basically filters out all images configured which don't have the name of this.image (which seems to be based on the ${project.artifactId)
https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java#L249

we should just omit the filtering for fabric8-maven-plugin I think?

**Comment by jstrachan** [comment]
BTW here's an example of a failing build (it was not building the image defined in the <configuration>) that I fixed via defining a `docker.image` property 
https://github.com/fabric8io/fabric8-devops/pull/513/commits/41ecb88ebd93a3e8677c1bde59a600d992b967f8

**Comment by rhuss** [comment]
Sorry, I don't get the issue.

Actually the **strong recommendation is to avoid `docker.image` in the pom.xml** as it is supposed to be used only from outside with a `-Ddocker.image` property.

I'm going to rename this to `docker.filter` for 0.17.1 (due tomorrow) to finally avoid all this confusion.

However, I still dont get this particular issue. `docker.image` has no default (wouldn't make sense anyway), so I wonder who else is setting `docker.image` here ??

**Comment by rhuss** [comment]
If you refer to the fabric8-devops, then the root cause it, that ${docker.image} is set in the parent pom.xml and hence all child poms must use then of course use the same name. 

I'm going to clean this up a bit.

**Comment by rhuss** [comment]
@jstrachan : Going to close this issue, since I believe it was due to a particular setup. Feel free to reopen in case.

btw, `docker.image` usable as project property for a filte was one of my worst ideas for d-m-p ;-). Everybody calls her image property "docker.image"

**Comment by nilaysaha** [comment]
@rhuss : What is the best strategy to deal with nested pom.xml. In this case I have parent pom.xml where I specify the docker configuration. And in all the nested pom.xml mention just name of the plugin. Also some variables like
`<properties>                                                                                                                                             
      <docker-version-suffix>${deployment-env}_${timestamp}_${git.commit.id.abbrev}</docker-version-suffix>
    </properties>
`
When I build the repository with structure like this

`
 pom.xml
  - module1
       - pom.xml
 - module2
      - pom.xml
 - module3
    - pom.xml
`
would like to build docker images only for module1,module2 and module3. For parent it makes no sense to have a docker image and all content is in modules....

Currently executing the build like this:
`
mvn clean dependency:copy-dependencies package -DskipTests -Ddeployment-env=staging -Dtimestamp=`date +%s` docker:build -X
`
Any clue would be great ?

And best would have been to coagulate all the modules into a single .jar file and make a single docker container from the single .jar file. But that is the next step....
